### ISSUE TITLE
【Review】MVPリリース

### ISSUE THREAD

**Issue by topi0247** [topi0247/Project-AStoryer#170]
## 各種情報
サービス名【AStoryer - あすとりや -】
サービスURL [https://astoryer.vercel.app](https://astoryer.vercel.app) 

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録
   - [x] メール・パスワード
   - [ ] ゲストログイン
- [ ] アカウント
   - [ ] アイコン
   - [ ] プロフィール
- [x] イラスト
   - [x] 一覧
   - [x] 投稿（タグ付けにてオートコンプリート）
   - [x] 編集※画像の差し替えではなくキャプションの編集のみ
   - [x] 削除
   - [x] 検索（マルチ検索・オートコンプリート）
- [x] ハッシュタグ
   - [x] 任意のタグ
   - [x] シナリオ名
   - [x] TRPGのシステム設定
- [x] いいね
- [ ] コメント
- [ ] ブックマーク
- [ ] フォロー機能
- [ ] 公開範囲の設定
   - [x] 全体公開（未ログイン可）
   - [x] URLを知っている人のみ（未ログイン可）
   - [ ] フォロワー
- [ ] 通知
   - [ ] メールアドレス宛
- [ ] Xシェア機能

### 未実装項目
下記は本リリースにて実装予定です。
MVPという観点から一旦なくても問題なさそうな項目を削ぎ落としました。
- [ ] アカウント
   - [ ] アイコン
   - [ ] プロフィール
- [ ] コメント
- [ ] ブックマーク
- [ ] フォロー機能
- [ ] 公開範囲の設定
   - [ ] フォロワー
- [ ] 通知
   - [ ] メールアドレス宛
- [ ] Xシェア機能

以下は実装から外した項目です
- ゲストログイン
   ⇨ 未ログインでも閲覧が可能であり、アプリの内容がわかるため

### 追加実装
以下はMVP時点では未実装予定でしたが実装したものです
- 国際化（ただし現在は日本語のみとなっています）
- SNS認証
   - Googleアカウント
   - Discordアカウント
- メールアドレス変更

## サービスイメージがわかるようなスクリーンショット等
| トップ画面 | 検索結果 |
| --- | --- |
| <img src="https://i.gyazo.com/1a8c5f546bf9da1c171f62ddaf04e227.png" width="400px" /> | <img src="https://i.gyazo.com/199c99dd7360889919207535a3b0b9ea.png" width="400px" /> |

| イラスト詳細 | イラスト投稿 |
| --- | --- |
| <img src="https://i.gyazo.com/199c99dd7360889919207535a3b0b9ea.png" width="500px" /> | <img src="https://i.gyazo.com/ccd85641e06db5cdf98d0d59c91b3bb2.gif" width="330px" /> |

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
