### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by topi0247** [topi0247/Project-AStoryer#76]
# 概要
GitHubProjectsにてissueとおおよその実装順を洗い出しました。
[ProjectsURL](https://github.com/users/topi0247/projects/3)

## 実装予定の機能
- [ ] メールアドレス・パスワードによる認証
- [ ] ゲストログイン
- [ ] イラスト投稿
- [ ] ステートに応じたイラスト編集
   - [ ] 下書きではイラストの編集も可能
   - [ ] 公開済みならイラストのみ編集不可
- [ ] 通知機能
   - [ ] メールへの通知
   - [ ] アプリ内通知
- [ ] オートコンプリート
- [ ] マルチ検索
- [ ] Xシェア機能
- [ ] 画像投稿機能（ユーザーアイコンやヘッダー）
- [ ] ブックマーク
- [ ] いいね
- [ ] フォロー
- [ ] 公開範囲の限定

## 必要なページ
- [ ] ホーム
- [ ] 新規登録
- [ ] ログイン
- [ ] イラスト一覧
- [ ] イラスト検索時の一覧
- [ ] イラスト詳細
- [ ] イラスト投稿
- [ ] イラスト編集
- [ ] マイページ
   - [ ] 投稿一覧
   - [ ] ブックマーク一覧
   - [ ] フォロー一覧
   - [ ] フォロワー一覧
- [ ] アカウント設定
- [ ] 利用規約
- [ ] プライバシーポリシー

## モーダル
- [ ] ログイン
（ゲストログインや未ログイン時にサービスを使っており、ログイン限定機能を使おうとしたときに表示するもの）
- [ ] 投稿完了時
- [ ] 下書き保存時
- [ ] 投稿削除
- [ ] マイページ編集
- [ ] 検索オプション

## その他
- [ ] メニューバー
   - [ ] マイページ（投稿一覧・ブックマーク）
   - [ ] フォロー人数
   - [ ] フォロワー人数
   - [ ] 設定
   - [ ] ログアウト

上記レビューのほど、よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
LGTMです！
